// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NetCoreMVC.Models.DBModel
{
    public partial class dbUser
    {
        public Guid ID { get; set; }
        [Display(Name = "用戶名稱")]
        [Required(ErrorMessage ="員工姓名為必填項目!")]
        public string Name { get; set; }
        [Display(Name = "員工編號")]
        public string EmpNo { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string BirthDay { get; set; }

    }
}