// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NetCoreMVC.Models.DBModel
{
    public partial class dbUser
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
        public string EmpNo { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
    }
}